// features/posts/postsSlice.js
//
// Core slice for Experiment 2. Demonstrates:
//   - createEntityAdapter for state normalization (section 3 of the PDF)
//   - createAsyncThunk for async fetching with pending/fulfilled/rejected (section 2)
//   - Full CRUD reducers (Assignment 1)
//   - Separation of data state (ids/entities) from UI state (loading/error/filters)

import { createSlice, createEntityAdapter, createAsyncThunk, nanoid } from "@reduxjs/toolkit";
import { fetchPostsFromServer } from "../../api/postsApi";

// The adapter defines how posts are stored: as a flat { ids: [], entities: {} }
// lookup table instead of a deeply nested array. Sorted by newest first.
const postsAdapter = createEntityAdapter({
  sortComparer: (a, b) => new Date(b.createdAt) - new Date(a.createdAt)
});

// Async thunk: simulates fetching posts from a backend/JSONPlaceholder-style API.
// RTK automatically generates fetchPosts.pending / .fulfilled / .rejected action types.
export const fetchPosts = createAsyncThunk("posts/fetchPosts", async (_, { rejectWithValue }) => {
  try {
    const data = await fetchPostsFromServer();
    return data;
  } catch (err) {
    // rejectWithValue lets the component read a clean error message from action.payload
    return rejectWithValue(err.message || "Failed to fetch posts");
  }
});

// initialState mixes the adapter's normalized shape with UI-only flags,
// following the "separation of data state and UI state" pattern from the PDF.
const initialState = postsAdapter.getInitialState({
  loading: false, // true while fetchPosts is pending
  error: null, // holds error message if fetchPosts is rejected
  searchTerm: "", // UI state: current search box value
  platformFilter: "all" // UI state: currently selected platform filter
});

const postsSlice = createSlice({
  name: "posts",
  initialState,
  reducers: {
    // ---- CRUD: Create ----
    addPost: {
      reducer(state, action) {
        postsAdapter.addOne(state, action.payload);
      },
      // prepare() builds the full post object (id + timestamp) from simple UI inputs,
      // keeping the component free of ID-generation / timestamp logic.
      prepare({ title, content, platform }) {
        return {
          payload: {
            id: nanoid(),
            title,
            content,
            platform,
            createdAt: new Date().toISOString()
          }
        };
      }
    },
    // ---- CRUD: Update / Edit ----
    updatePost(state, action) {
      const { id, changes } = action.payload;
      postsAdapter.updateOne(state, { id, changes });
    },
    // ---- CRUD: Delete ----
    deletePost(state, action) {
      postsAdapter.removeOne(state, action.payload);
    },
    // ---- UI state reducers (kept separate from data reducers) ----
    setSearchTerm(state, action) {
      state.searchTerm = action.payload;
    },
    setPlatformFilter(state, action) {
      state.platformFilter = action.payload;
    }
  },
  // extraReducers handles actions dispatched from OUTSIDE this slice,
  // specifically the three lifecycle actions generated by fetchPosts.
  // This mirrors a finite state machine: pending -> fulfilled | rejected.
  extraReducers: (builder) => {
    builder
      .addCase(fetchPosts.pending, (state) => {
        state.loading = true;
        state.error = null;
      })
      .addCase(fetchPosts.fulfilled, (state, action) => {
        state.loading = false;
        // setAll replaces the normalized collection with the freshly fetched data.
        postsAdapter.setAll(state, action.payload);
      })
      .addCase(fetchPosts.rejected, (state, action) => {
        state.loading = false;
        state.error = action.payload || "Unknown error while fetching posts";
      });
  }
});

export const { addPost, updatePost, deletePost, setSearchTerm, setPlatformFilter } =
  postsSlice.actions;

// Adapter-generated base selectors (selectAll, selectById, selectIds, selectEntities, selectTotal),
// scoped to the `posts` slice. Additional derived/memoized selectors live in postSelectors.js.
export const postsSelectors = postsAdapter.getSelectors((state) => state.posts);

export default postsSlice.reducer;
